version: '3'
services:
  db:
    image: postgres:latest
    environment:
        POSTGRES_DB: "postgres"
        POSTGRES_USER: "nik"
        POSTGRES_PASSWORD: "12345678"
    ports:
      - 5432:5432